/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FRMGuiaRemision.java
 *
 * Created on 28/09/2012, 04:08:09 AM
 */

package Vistas;
import javax.swing.table.AbstractTableModel;
import Main.Main;
import java.util.ArrayList;
import Beans.GuiaRemision;
/**
 *
 * @author jorge
 */
public class FRMGuiaRemision extends javax.swing.JInternalFrame {
    
    class GuiaRemisionTableModel extends AbstractTableModel{
        public ArrayList<GuiaRemision> guiasremision=Main.servicioGuiaRemision.getGuiasRemision();
        String [] nombreColumna = {"Id guía","Fecha", "monto"};
        
        @Override
        public int getRowCount() {
            return guiasremision.size();
        }
        
        @Override
        public int getColumnCount() {
            return 3;
        }
        
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            GuiaRemision guiaremision=guiasremision.get(rowIndex);
            switch(columnIndex){
                case 0: return "" + guiaremision.getId();
                case 1: return guiaremision.getFecha();
                case 2: return guiaremision.getTotal();
            }
            return null;
        }
        @Override
        public String getColumnName(int columna){
            return nombreColumna[columna];
        }
    }
    
    private GuiaRemisionTableModel grTableModel=new GuiaRemisionTableModel();
    private int idSeleccionado=0;
    /** Creates new form FRMGuiaRemision */
    public FRMGuiaRemision() {
        initComponents();
        tablaGuiasRemision.setModel(grTableModel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        txFecha = new javax.swing.JTextField();
        txMonto = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGuiasRemision = new javax.swing.JTable();
        
        jLabel1.setText("Id");
        
        jLabel2.setText("Monto total");
        
        jLabel3.setText("Fecha");
        
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Relación de guias de remisión"));
        
        tablaGuiasRemision.setModel(new javax.swing.table.DefaultTableModel(
                                                                            new Object [][] {
                                                                                {null, null, null, null},
                                                                                {null, null, null, null},
                                                                                {null, null, null, null},
                                                                                {null, null, null, null}
                                                                            },
                                                                            new String [] {
                                                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                                                            }
                                                                            ));
        jScrollPane1.setViewportView(tablaGuiasRemision);
        
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                                         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGap(0, 346, Short.MAX_VALUE)
                                         .addGroup(jPanel2Layout.createSequentialGroup()
                                                   .addContainerGap()
                                                   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                                   .addContainerGap())
                                         );
        jPanel2Layout.setVerticalGroup(
                                       jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 226, Short.MAX_VALUE)
                                       .addGroup(jPanel2Layout.createSequentialGroup()
                                                 .addContainerGap()
                                                 .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                                 .addContainerGap())
                                       );
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                                         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                   .addGap(20, 20, 20)
                                                   .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                             .addComponent(jLabel2)
                                                             .addComponent(jLabel1)
                                                             .addComponent(jLabel3))
                                                   .addGap(18, 18, 18)
                                                   .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                                       .addComponent(txMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                                                       .addContainerGap())
                                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                                       .addComponent(txFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                                                       .addContainerGap())
                                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                                       .addComponent(txId, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                                       .addGap(112, 112, 112))))
                                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                   .addContainerGap(78, Short.MAX_VALUE)
                                                   .addComponent(btnAceptar)
                                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                   .addComponent(btnEditar)
                                                   .addGap(18, 18, 18)
                                                   .addComponent(btnEliminar)
                                                   .addGap(71, 71, 71))
                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                   .addContainerGap()
                                                   .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                   .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                         );
        jPanel1Layout.setVerticalGroup(
                                       jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                 .addGap(46, 46, 46)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(jLabel1)
                                                           .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addGap(18, 18, 18)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                           .addComponent(jLabel3)
                                                           .addComponent(txFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addGap(18, 18, 18)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                           .addComponent(jLabel2)
                                                           .addComponent(txMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addGap(18, 18, 18)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(btnAceptar)
                                                           .addComponent(btnEditar)
                                                           .addComponent(btnEliminar))
                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                 .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                 .addContainerGap())
                                       );
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                  .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addContainerGap())
                                  );
        layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addContainerGap())
                                );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        GuiaRemision grem=new GuiaRemision();
        grem.setId(Integer.parseInt(txId.getText()));
        java.util.Date fecha=new java.util.Date(txFecha.getText());
        grem.setFecha(fecha);
        grem.setTotal(Double.parseDouble(txMonto.getText()));
        
        Main.servicioGuiaRemision.agregarGuiaRemision(grem);
        actualizarTabla();
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (idSeleccionado!=0){
            GuiaRemision grem=new GuiaRemision();
            grem.setId(idSeleccionado);
            java.util.Date fecha=new java.util.Date(txFecha.getText());
            grem.setFecha(fecha);
            grem.setTotal(Double.parseDouble(txMonto.getText()));
            
            Main.servicioGuiaRemision.editarGuiaRemision(grem);
            actualizarTabla();
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idSeleccionado!=0){
            Main.servicioGuiaRemision.eliminaGuiaRemision(idSeleccionado);
            actualizarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    public void actualizarTabla(){
        grTableModel.guiasremision = Main.servicioGuiaRemision.getGuiasRemision();
        grTableModel.fireTableChanged(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaGuiasRemision;
    private javax.swing.JTextField txFecha;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txMonto;
    // End of variables declaration//GEN-END:variables
    
}
